# Generated by Django 5.2.11 on 2026-02-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGOProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteers', models.IntegerField(default=0)),
                ('ambulances', models.IntegerField(default=0)),
                ('efficiency_score', models.FloatField(default=0)),
            ],
        ),
    ]
